### ISSUE TITLE
模式很好，但是要做的太多了。

### ISSUE THREAD

**Issue by Jarlene** [androidflux/flux#3]
首先网络请求，IO操作等需要线程的动作没有考虑。这个太简单了，需要完善的还有很多

**Comment by SelfImpro** [comment]
这里只提供框架的思路，具体细节可以根据自己习惯来，我觉得挺好，定义太细了反而是限制了。

**Comment by ntop001** [comment]
对，你说的这些在 androidflux.github.io 上有写的，只是太忙了，没有时间去完善demo
