### ISSUE TITLE
Dispatcher中的post

### ISSUE THREAD

**Issue by hurimeng** [androidflux/flux#4]
难道要因为一个随便的点击事件action就遍历所有Store

**Comment by Sloaix** [comment]
Store的消息订阅和取消订阅都是在Fragment/Activity的生命周期的开始和结束范围内的，换句话说，Store的生命周期应该不超过Fragment/Activity的生命周期。

依此看来，移动设备上，一屏有很少会有多个处于创建和销毁之间生命周期的Fragment(我不排除Pad下多Fragment布局或者组件化Fragment的存在)。同时Activity正常情况下也应是单个的。

我的意思就是Dispatcher每次分发的Store绝对不会超过一个很大的数字，甚至可以说一般的项目不会超过个位数。

所以，我觉得遍历的资源消耗是可以接受的，Flux带来的更清晰的数据流向，更好的代码可跟踪性，和可测试性完全可以抵消这点。

其实你可以让Store持有Dispatcher的引用，改造一下Dispatcher，让Dispatcher支持定向分发，例如
store.dispatch(action);或者dispatcher.dispatch(action,store);这样的方式，只有对应的store能收到分发的action。

最后，Flux只是一种架构规范，没有最好的，只有最适合的，你完全可以在自己的项目中进行对应的修改和调整，教条主义是不可取的，应该融会贯通。

**Comment by ntop001** [comment]
@hellosad  一个Action遍历所有Store这种设计在Flux/Redux框架中都是默认行为，这种设计的出发点是完全解耦Action和Store的关系这样在添加/移除Store都会变得容易。在实际开发中Store的数量确实很多的情况，如 @lsxiao 所言，Flux并没有强制这种行为，完全可以修改Dispatcher的实现，把Action直接路由到相关的Store，当然这需要在Store初始化的是订阅感兴趣的Action，提前定制策略。
